name: CI/CD - Atualização de Versão com Java

on:
  push:
    branches:
      - '**'  # Isso irá acionar o workflow para qualquer branch (ajustado para todas as branches)
    paths:
      - 'pfizer/**'
      - 'pdvsync/**'
      - '**/versao.json'  # Aciona para qualquer alteração no versao.json

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
 
    - name: Configuração do Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Usando a distribuição correta (temurin)
        cache: 'maven'  # Optional: cache de dependências do Maven, se necessário


    - name: Copiar o JAR do repositório
      run: |
        # Copia o JAR da pasta versao-control para o diretório target (onde será executado)
        mkdir -p target  # Cria o diretório onde o JAR será colocado
        cp versao-control/versao-control.jar target/  # Copia o JAR para o diretório target

   # - name: Configuração de autenticação no Git
   #   run: |
   #     git config --global user.name "GitHub Actions"
   #     git config --global user.email "actions@github.com"
   #     git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Executar o arquivo JAR para atualizar a versão
      run: |
        java -jar target/versao-control.jar  # Executa o arquivo JAR

    #- name: Commit e Push das mudanças
    #  run: |
    #    git add pfizer/versao.json pdvsync/versao.json
    #    git commit -m "Incrementando versão nos arquivos versao.json"
    #    git push
